defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  host: flame.mongohq.com
  port: 27028
  username: monsters
  password: startupweekend
  database: monsters

test:
  <<: *defaults
  database: monsters_test

# set these environment variables on your prod server
production:
  host: flame.mongohq.com
  port: 27028
  username: monsters
  password: startupweekend
  database: monsters

  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>